package com.rksdev.security.api;

/**
 * Service Provider Interface (SPI) for handling password reset operations.
 * Any microservice that wants to enable the forgot/reset password endpoints
 * must provide a concrete implementation of this interface as a Spring Bean.
 */
public interface PluggablePasswordResetHandler {

    /**
     * Triggered when a user requests a password reset link.
     * The implementing service should save this token alongside an expiration timestamp
     * (e.g., 15 minutes) and trigger an email delivery containing the token to the user.
     *
     * @param email       The email address submitted by the user.
     * @param secureToken A cryptographically secure, unique string (UUID) generated by the library.
     */
    void handleResetRequested(String email, String secureToken);

    /**
     * Triggered when a user submits a new password along with their token.
     * The implementing service must look up the token, verify it belongs to a valid user,
     * check that it hasn't expired, update the user's password with the new hash,
     * and immediately invalidate/delete the token.
     *
     * @param token                The unique token string submitted from the client.
     * @param encryptedNewPassword The new password, already securely hashed by the library using BCrypt.
     * @return true if the password was successfully reset; false if the token was invalid or expired.
     */
    boolean handlePasswordReset(String token, String encryptedNewPassword);
}